{% macro get_orders_columns() %}

{% set columns = [
    {"name": "amazon_order_id", "datatype": dbt.type_string()},
    {"name": "automated_shipping_setting_automated_carrier", "datatype": dbt.type_string()},
    {"name": "automated_shipping_setting_automated_ship_method", "datatype": dbt.type_string()},
    {"name": "automated_shipping_setting_has_automated_shipping_settings", "datatype": dbt.type_boolean()},
    {"name": "buyer_info_buyer_email", "datatype": dbt.type_string()},
    {"name": "buyer_info_buyer_name", "datatype": dbt.type_string()},
    {"name": "buyer_info_purchase_order_number", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_address_line_1", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_address_line_2", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_address_line_3", "datatype": dbt.type_int()},
    {"name": "default_ship_from_location_address_type", "datatype": dbt.type_int()},
    {"name": "default_ship_from_location_city", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_country_code", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_county", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_district", "datatype": dbt.type_int()},
    {"name": "default_ship_from_location_municipality", "datatype": dbt.type_int()},
    {"name": "default_ship_from_location_name", "datatype": dbt.type_string()},
    {"name": "default_ship_from_location_phone", "datatype": dbt.type_int()},
    {"name": "default_ship_from_location_postal_code", "datatype": dbt.type_int()},
    {"name": "default_ship_from_location_state_or_region", "datatype": dbt.type_int()},
    {"name": "earliest_delivery_date", "datatype": dbt.type_string()},
    {"name": "earliest_ship_date", "datatype": dbt.type_string()},
    {"name": "easy_ship_shipment_status", "datatype": dbt.type_string()},
    {"name": "electronic_invoice_status", "datatype": dbt.type_string()},
    {"name": "fulfillment_channel", "datatype": dbt.type_string()},
    {"name": "fulfillment_supply_source_id", "datatype": dbt.type_string()},
    {"name": "has_regulated_items", "datatype": dbt.type_boolean()},
    {"name": "is_access_point_order", "datatype": dbt.type_boolean()},
    {"name": "is_business_order", "datatype": dbt.type_boolean()},
    {"name": "is_estimated_ship_date_set", "datatype": dbt.type_boolean()},
    {"name": "is_global_express_enabled", "datatype": dbt.type_boolean()},
    {"name": "is_iba", "datatype": dbt.type_boolean()},
    {"name": "is_ispu", "datatype": dbt.type_boolean()},
    {"name": "is_premium_order", "datatype": dbt.type_boolean()},
    {"name": "is_prime", "datatype": dbt.type_boolean()},
    {"name": "is_replacement_order", "datatype": dbt.type_boolean()},
    {"name": "is_sold_by_ab", "datatype": dbt.type_boolean()},
    {"name": "last_update_date", "datatype": dbt.type_timestamp()},
    {"name": "latest_delivery_date", "datatype": dbt.type_timestamp()},
    {"name": "latest_ship_date", "datatype": dbt.type_timestamp()},
    {"name": "marketplace_id", "datatype": dbt.type_string()},
    {"name": "number_of_items_shipped", "datatype": dbt.type_int()},
    {"name": "number_of_items_unshipped", "datatype": dbt.type_int()},
    {"name": "order_channel", "datatype": dbt.type_string()},
    {"name": "order_status", "datatype": dbt.type_string()},
    {"name": "order_total_amount", "datatype": dbt.type_string()},
    {"name": "order_total_currency_code", "datatype": dbt.type_string()},
    {"name": "order_type", "datatype": dbt.type_string()},
    {"name": "payment_method", "datatype": dbt.type_string()},
    {"name": "promise_response_due_date", "datatype": dbt.type_timestamp()},
    {"name": "purchase_date", "datatype": dbt.type_timestamp()},
    {"name": "replaced_order_id", "datatype": dbt.type_string()},
    {"name": "sales_channel", "datatype": dbt.type_string()},
    {"name": "seller_order_id", "datatype": dbt.type_string()},
    {"name": "ship_service_level", "datatype": dbt.type_string()},
    {"name": "shipment_service_level_category", "datatype": dbt.type_string()},
    {"name": "shipping_address_address_line_1", "datatype": dbt.type_string()},
    {"name": "shipping_address_address_line_2", "datatype": dbt.type_int()},
    {"name": "shipping_address_address_line_3", "datatype": dbt.type_int()},
    {"name": "shipping_address_address_type", "datatype": dbt.type_int()},
    {"name": "shipping_address_city", "datatype": dbt.type_string()},
    {"name": "shipping_address_country_code", "datatype": dbt.type_int()},
    {"name": "shipping_address_county", "datatype": dbt.type_int()},
    {"name": "shipping_address_district", "datatype": dbt.type_int()},
    {"name": "shipping_address_municipality", "datatype": dbt.type_int()},
    {"name": "shipping_address_name", "datatype": dbt.type_int()},
    {"name": "shipping_address_phone", "datatype": dbt.type_int()},
    {"name": "shipping_address_postal_code", "datatype": dbt.type_int()},
    {"name": "shipping_address_state_or_region", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}
